# Generated by Django 3.2.3 on 2021-06-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProuctCategory',
            new_name='ProductCategory',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_img',
            field=models.ImageField(blank=True, upload_to='products_img'),
        ),
    ]
