# Generated by Django 3.2.3 on 2021-06-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
        ),
    ]
