# Generated by Django 3.2.3 on 2021-06-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_category_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
