# Generated by Django 3.2.3 on 2021-06-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_newproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewProducts',
        ),
    ]
